### ISSUE TITLE
Nearest User Node

### ISSUE THREAD

**Issue by DoubleStyx** [Xlinka/NeosPlus#57] opened 2022-08-23 18:31 UTC
Like Nearest User Head, but gets the User ref instead.

**Comment by LeCloutPanda** [comment] 2022-08-23 18:55
Duplicate of [#39](https://github.com/Xlinka/NeosPlus/issues/39) but looking into it anyways

**Comment by DoubleStyx** [comment] 2022-08-23 19:21
We probably shouldn't have issues like #39 listing two separate nodes like that anyway. I think keeping this issue open is justifiable.

**Comment by reality-exe** [comment] 2022-08-23 23:48
Yeah i should've just made a new issue for that.

**Comment by jeanahelver** [comment] 2022-08-25 02:27
sorry to add to this but would it be possible to get a list for ignore user similar to + , format or index of first match
finding the second nearest user is difficult in vanilla

**Comment by LeCloutPanda** [comment] 2022-08-25 02:45
It's possible just gotta look into it more, hopefully by the next release it's done

**Comment by Xlinka** [comment] 2022-08-25 16:43
is this a issue on the main github ?

**Comment by DoubleStyx** [comment] 2022-08-25 21:17
> is this a issue on the main github ?

Not that I know of.

**Comment by Xlinka** [comment] 2022-08-25 21:17
Please make one so I can then link them.

**Comment by DoubleStyx** [comment] 2022-08-25 21:22
Hm, Nearest User Hand actually has an output for the User ref of the nearest user's hand. Now I'm confused. Did I just create an issue for something that already had a solution? Well anyway, I guess we could add nodes for other avatar points, like the hips, foot, chest, and so on. I'm not sure what the use case for such nodes would be, but it is an interesting proposition.

**Comment by reality-exe** [comment] 2022-08-25 21:30
There's also one for `Nearest User Head`. However it would be nice to have just the user reference

**Comment by DoubleStyx** [comment] 2022-08-25 21:41
I don't think there's any harm in having a single node that provides multiple related outputs. There is a small performance cost involved in evaluating any outputs that aren't used, but many nodes already follow this output-batching design philosophy.

**Closed** 2023-03-20 15:51 UTC
Labels: New Node, LogiX
