### ISSUE TITLE
integrate BEPUv2 rigid bodies 

### ISSUE THREAD

**Issue by epicEaston197** [Xlinka/NeosPlus#73] opened 2022-08-31 22:12 UTC
I would like BEPUv2  rigid bodies to be integrated into Neos Plus  so that I can create buildings that can be destroyed along with a lot of other things

**Comment by DoubleStyx** [comment] 2022-09-01 00:28
Probably duplicate of #55.

**Comment by Frozenreflex** [comment] 2022-09-01 00:30
Is indeed a duplicate of #55.

**Closed by Frozenreflex** 2022-09-01 00:30 UTC
Labels: duplicate
